coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: number
        threshold: 60%
        # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
        flags:
          - frontend
        paths:
          - src/frontend
