name:                lambda-cube
version:             0.2.0.2
github:              "AdamLassiter/lambda-cube"
license:             MIT
author:              "Adam Lassiter"
maintainer:          "adamlassiter96@gmail.com"
copyright:           "2021 Adam Lassiter"

extra-source-files:
- README.md

synopsis:            Some thoughts on Calculus of Constructions
category:            Compiler

description:         Please see the README on GitHub at <https://github.com/AdamLassiter/lambda-cube#readme>

dependencies:
- base >=4.15
- text >=1.2 
- bytestring >=0.10
- extra >=1.7
- filepath >=1.4 
- file-embed >=0.0.15
- monad-control >=1.0
- logging >=3.0
- haskeline >=0.8
- containers >=0.6
- time >=1.9
- criterion >=1.5 

library:
  source-dirs: src
  cpp-options:
  - -DLOGINFO
  dependencies:
  - base
  - text
  - bytestring
  - extra
  - filepath
  - file-embed
  - monad-control
  - logging

executables:
  lambda-cube-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - lambda-cube
    - base
    - haskeline

tests:
  lambda-cube-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - lambda-cube
    - base
    - containers
    - time
    - filepath

benchmarks:
  lambda-cube-bench:
    main:                Crit.hs
    source-dirs:         bench
    ghc-options:
    - -O2
    - -fprof-auto
    - -fprof-cafs
    - -rtsopts
    - '"-with-rtsopts=-pj -h"'
    # - '"-with-rtsopts=-h -P -xc"'
    dependencies:
    - lambda-cube
    - base
    - criterion
