name:                lambda-cube
version:             0.2.0.1
github:              "AdamLassiter/lambda-cube"
license:             MIT
author:              "Adam Lassiter"
maintainer:          "adamlassiter96@gmail.com"
copyright:           "2021 Adam Lassiter"

extra-source-files:
- README.md

synopsis:            Some thoughts on Calculus of Constructions
category:            Compiler

description:         Please see the README on GitHub at <https://github.com/AdamLassiter/lambda-cube#readme>

dependencies:
- base >= 4.16 && < 5
- text >=1.2 && <1.3
- bytestring >=0.10 && <0.11
- extra >=1.6 && <1.8
- filepath >=1.4 && <1.5
- file-embed >=0.0.15 && <0.0.16
- monad-control >=1.0 && <1.1
- logging >=3.0 && <3.1
- haskeline >=0.8 && <0.9
- criterion >=1.5 && <1.6

library:
  source-dirs: src
  cpp-options:
  - -DLOGGING
  dependencies:
  - base
  - text
  - bytestring
  - extra
  - filepath
  - file-embed
  - monad-control
  - logging

executables:
  lambda-cube-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - lambda-cube
    - base
    - haskeline

tests:
  lambda-cube-test:
    main:                Spec.hs
    source-dirs:         test
    cpp-options:
    - -DLOGGING
    dependencies:
    - lambda-cube
    - base
    - filepath

benchmarks:
  lambda-cube-bench:
    main:                Crit.hs
    source-dirs:         bench
    ghc-options:
    - -O2
    dependencies:
    - lambda-cube
    - base
    - criterion
