name:                lambda-cube
version:             0.2.0.0
github:              "AdamLassiter/lambda-cube"
license:             MIT
author:              "Adam Lassiter"
maintainer:          "adamlassiter96@gmail.com"
copyright:           "2021 Adam Lassiter"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Some thoughts on Calculus of Constructions
category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AdamLassiter/lambda-cube#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  cpp-options:
  - -DTRACING=false
  dependencies:
  - base >=4.15 && <5
  - text >=1.2 && <1.3
  - bytestring >=0.10 && <0.11
  - extra >=1.6 && <1.8
  - filepath >=1.4 && <1.5
  - file-embed >=0.0.15 && <0.0.16
  - monad-control >=1.0 && <1.1
  - logging >=3.0 && <3.1

executables:
  lambda-cube-exe:
    main:                Main.hs
    source-dirs:         app
    cpp-options:
    - -DTRACING=false
    dependencies:
    - lambda-cube
    - base >=4.7 && <5
    - haskeline >=0.8 && <0.9

tests:
  lambda-cube-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O0
    - -fprof-auto
    - -fprof-cafs
    - -rtsopts
    - '"-with-rtsopts=-P -h -xc"'
    cpp-options:
    - -DTRACING=false
    dependencies:
    - lambda-cube
    - base >=4.7 && <5
    - filepath >=1.4 && <1.5

benchmarks:
  lambda-cube-bench:
    main:                Crit.hs
    source-dirs:         bench
    ghc-options:
    - -O2
    - -fprof-auto
    - -fprof-cafs
    - -rtsopts
    - '"-with-rtsopts=-pj -h"'
    cpp-options:
    - -DTRACING=false
    dependencies:
    - lambda-cube
    - base >=4.7 && <5
    - criterion >=1.5 && <1.6
