#!/bin/sh -e

pname=`cat package.yaml | grep "name:" | awk '{ print $2 }'`
pvers=`cat package.yaml | grep "version:" | awk '{ print $2 }'`
echo ">>> Building Haddock for $pname"

rm -rf docs
mkdir docs
stack haddock --no-haddock-deps --haddock-arguments="--odir=./docs"
git add docs
