#!/bin/sh -e

pname=`cat package.yaml | grep "name:" | awk '{ print $2 }'`
echo ">>> Building Haddock for $pname"

stack haddock --no-haddock-deps
doc_root=`stack path --local-doc-root`/$pname*
du -h $doc_root

rm -rf docs
mkdir docs
cp -r $doc_root/* docs
git add docs
