#!/bin/sh -e

git checkout master

pname=`cat package.yaml | grep "name:" | awk '{ print $2 }'`
echo ">>> Building Haddock for $pname"

stack haddock --no-haddock-deps
doc_root=`stack path --local-doc-root`/$pname*
du -h $doc_root

rm -rf doc
mkdir doc
cp -r $doc_root/* doc
git add doc
git commit -m "Automatic Haddock commit"
