name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4' # Exact version of ghc to use
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      # Build dependencies required by 'test' (and hpc-codecov)
      run: |
        stack --no-terminal --install-ghc test --only-dependencies
        stack install hpc-codecov
    - name: Build Library and Test
      # Build the package, its tests, and run the tests tracking code coverage
      run: |
        stack --no-terminal test --coverage

    - name: Report Codecov Coverage
      # Build coverage report and send to codecov.io
      run: |
        hpc-codecov --verbose --mix=$(stack path --dist-dir)/hpc -o codecov.json $(find $(stack path --local-hpc-root) -name '*.tix')
        bash <(curl -s https://codecov.io/bash)

    - name: Build gh-pages Documentation
      run: |
        git config --global user.email "23099842+github-actions-bot@users.noreply.github.com"
        git config --global user.name "GitHub Actions [Bot]"
        pname=`cat package.yaml | grep "name:" | awk '{ print $2 }'`
        time stack haddock --no-haddock-deps
        doc_root=`stack path --local-doc-root`/$pname*
        du -h $doc_root
        git branch -D gh-pages || echo "gh-pages branch didn't exist"
        git checkout --orphan gh-pages
        rm -rf *
        cp -r $doc_root/* .
        git add .
        git commit -m "Automatic Haddock commit"
    - name: Push to Branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
