name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10'
        cabal-version: '3.2'
    - name: Install CI tools
      run: |
        sudo apt-get install libcurl4 libcurl4-openssl-dev
        cabal install hpc-coveralls


    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build
      run: |
        cabal build

    - name: Run tests
      run: |
        cabal test

    - name: Generate test coverage
      run: |
        ln -s dist-newstyle/build/*/ghc-*/lambda-cube-*/ dist
        hpc-coveralls tests
